language: ruby
rvm:
  - 1.8.7
  - 1.9.2
notifications:
  email: false
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.18
install:
  - gem install bundler
  - bundle update
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.17
